package model;
// Generated 15-Feb-2017 2:38:53 PM by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Emptitle generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
public class Emptitle implements java.io.Serializable {

    /**
     * Employee title id.
     */
    private EmptitleId id;
    
    /**
     * Delete flag.
     */
    private short etDel;
    
    /**
     * Insert date.
     */
    private Date etInsDt;
    
    /**
     * Update date.
     */
    private Date etUpDt;

    /**
     * Default ctor.
     */
    public Emptitle() {
    }

    /**
     * Create an Emptitle.
     * @param id EmptitleId
     * @param etDel delete flag
     * @param etInsDt insert date
     * @param etUpDt update date
     */
    public Emptitle(EmptitleId id, short etDel, Date etInsDt, Date etUpDt) {
        this.id = id;
        this.etDel = etDel;
        this.etInsDt = etInsDt;
        this.etUpDt = etUpDt;
    }

    /**
     * Get id.
     * @return id
     */
    @EmbeddedId

    @AttributeOverrides({ @AttributeOverride(name = "etEmpId", column = @Column(name = "etEmpID", nullable = false)),
            @AttributeOverride(name = "etTitId", column = @Column(name = "etTitID", nullable = false)) })
    public EmptitleId getId() {
        return this.id;
    }

    /**
     * Set id.
     * @param id id
     */
    public void setId(EmptitleId id) {
        this.id = id;
    }

    /**
     * Get etDel.
     * @return etDel
     */
    @Column(name = "etDel", nullable = false)
    public short getEtDel() {
        return this.etDel;
    }

    /**
     * Set etDel.
     * @param etDel etDel
     */
    public void setEtDel(short etDel) {
        this.etDel = etDel;
    }

    /**
     * Get etInsDt.
     * @return etInsDt
     */
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "etInsDt", nullable = false, length = 19)
    public Date getEtInsDt() {
        return this.etInsDt;
    }

    /**
     * Set etInsDt.
     * @param etInsDt etInsDt
     */
    public void setEtInsDt(Date etInsDt) {
        this.etInsDt = etInsDt;
    }

    /**
     * Get etUpDt.
     * @return etUpDt
     */
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "etUpDt", nullable = false, length = 19)
    public Date getEtUpDt() {
        return this.etUpDt;
    }

    /**
     * Set etUpDt.
     * @param etUpDt etUpDt
     */
    public void setEtUpDt(Date etUpDt) {
        this.etUpDt = etUpDt;
    }

}
