package model;
// Generated 15-Feb-2017 2:38:53 PM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EmptitleId generated by hbm2java
 */
@Embeddable
public class EmptitleId implements java.io.Serializable {

    private int etEmpId;
    private short etTitId;

    public EmptitleId() {
    }

    public EmptitleId(int etEmpId, short etTitId) {
        this.etEmpId = etEmpId;
        this.etTitId = etTitId;
    }

    @Column(name = "etEmpID", nullable = false)
    public int getEtEmpId() {
        return this.etEmpId;
    }

    public void setEtEmpId(int etEmpId) {
        this.etEmpId = etEmpId;
    }

    @Column(name = "etTitID", nullable = false)
    public short getEtTitId() {
        return this.etTitId;
    }

    public void setEtTitId(short etTitId) {
        this.etTitId = etTitId;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof EmptitleId))
            return false;
        EmptitleId castOther = (EmptitleId) other;

        return (this.getEtEmpId() == castOther.getEtEmpId()) && (this.getEtTitId() == castOther.getEtTitId());
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getEtEmpId();
        result = 37 * result + this.getEtTitId();
        return result;
    }

}