package model;
// Generated 15-Feb-2017 2:38:53 PM by Hibernate Tools 3.5.0.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Empwp generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "Empwp")
public class Empwp implements java.io.Serializable {

    /**
     * Empwp id.
     */
    private EmpwpId id;
    
    /**
     * Assign date.
     */
    private Date ewAssDt;
    
    /**
     * Estimated hours.
     */
    private BigDecimal ewEstHrs;
    
    /**
     * Deleted flag.
     */
    private short ewDel;
    
    /**
     * Insert date.
     */
    private Date ewInsDt;
    
    /**
     * Update date.
     */
    private Date ewUpDt;

    /**
     * Default ctor.
     */
    public Empwp() {
    }

    /**
     * Create a Empwp.
     * @param id EmpwpId.
     * @param ewAssDt assign date.
     * @param ewDel delete flag
     * @param ewInsDt insert date
     * @param ewUpDt update date
     */
    public Empwp(EmpwpId id, Date ewAssDt, short ewDel, Date ewInsDt, Date ewUpDt) {
        this.id = id;
        this.ewAssDt = ewAssDt;
        this.ewDel = ewDel;
        this.ewInsDt = ewInsDt;
        this.ewUpDt = ewUpDt;
    }

    /**
     * Create a Empwp.
     * @param id EmpwpId
     * @param ewAssDt assign date
     * @param ewEstHrs estimated hours
     * @param ewDel delete flag
     * @param ewInsDt insert date
     * @param ewUpDt update date
     */
    public Empwp(EmpwpId id, Date ewAssDt, BigDecimal ewEstHrs, short ewDel, Date ewInsDt, Date ewUpDt) {
        this.id = id;
        this.ewAssDt = ewAssDt;
        this.ewEstHrs = ewEstHrs;
        this.ewDel = ewDel;
        this.ewInsDt = ewInsDt;
        this.ewUpDt = ewUpDt;
    }

    /**
     * Get id.
     * @return id
     */
    @EmbeddedId

    @AttributeOverrides({ @AttributeOverride(name = "ewEmpId", column = @Column(name = "ewEmpID", nullable = false)),
            @AttributeOverride(name = "ewProjNo", column = @Column(name = "ewProjNo", nullable = false)),
            @AttributeOverride(name = "ewWpNo", column = @Column(name = "ewWpNo", nullable = false, length = 8)) })
    public EmpwpId getId() {
        return this.id;
    }

    /**
     * Set id.
     * @param id id
     */
    public void setId(EmpwpId id) {
        this.id = id;
    }

    /**
     * Get ewAssDt.
     * @return ewAssDt
     */
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "ewAssDt", nullable = false, length = 19)
    public Date getEwAssDt() {
        return this.ewAssDt;
    }

    /**
     * Set ewAssDt.
     * @param ewAssDt ewAssDt
     */
    public void setEwAssDt(Date ewAssDt) {
        this.ewAssDt = ewAssDt;
    }

    /**
     * Get ewEstHrs.
     * @return ewEstHrs
     */
    @Column(name = "ewEstHrs", precision = 5)
    public BigDecimal getEwEstHrs() {
        return this.ewEstHrs;
    }

    /**
     * Set ewEstHrs.
     * @param ewEstHrs ewEstHrs
     */
    public void setEwEstHrs(BigDecimal ewEstHrs) {
        this.ewEstHrs = ewEstHrs;
    }

    /**
     * Get ewDel.
     * @return ewDel
     */
    @Column(name = "ewDel", nullable = false)
    public short getEwDel() {
        return this.ewDel;
    }

    /**
     * Set ewDel.
     * @param ewDel ewDel
     */
    public void setEwDel(short ewDel) {
        this.ewDel = ewDel;
    }

    /**
     * Get ewInsDt.
     * @return ewInsDt
     */
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "ewInsDt", nullable = false, length = 19)
    public Date getEwInsDt() {
        return this.ewInsDt;
    }

    /**
     * Set ewInsDt.
     * @param ewInsDt ewInsDt
     */
    public void setEwInsDt(Date ewInsDt) {
        this.ewInsDt = ewInsDt;
    }

    /**
     * Get ewUpDt.
     * @return ewUpDt
     */
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "ewUpDt", nullable = false, length = 19)
    public Date getEwUpDt() {
        return this.ewUpDt;
    }

    /**
     * Set ewUpDt.
     * @param ewUpDt ewUpDt
     */
    public void setEwUpDt(Date ewUpDt) {
        this.ewUpDt = ewUpDt;
    }

}