package model;
// Generated 15-Feb-2017 2:38:53 PM by Hibernate Tools 3.5.0.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Empwp generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "Empwp")
public class Empwp implements java.io.Serializable {

    private EmpwpId id;
    private Date ewAssDt;
    private BigDecimal ewEstHrs;
    private short ewDel;
    private Date ewInsDt;
    private Date ewUpDt;

    public Empwp() {
    }

    public Empwp(EmpwpId id, Date ewAssDt, short ewDel, Date ewInsDt, Date ewUpDt) {
        this.id = id;
        this.ewAssDt = ewAssDt;
        this.ewDel = ewDel;
        this.ewInsDt = ewInsDt;
        this.ewUpDt = ewUpDt;
    }

    public Empwp(EmpwpId id, Date ewAssDt, BigDecimal ewEstHrs, short ewDel, Date ewInsDt, Date ewUpDt) {
        this.id = id;
        this.ewAssDt = ewAssDt;
        this.ewEstHrs = ewEstHrs;
        this.ewDel = ewDel;
        this.ewInsDt = ewInsDt;
        this.ewUpDt = ewUpDt;
    }

    @EmbeddedId

    @AttributeOverrides({ @AttributeOverride(name = "ewEmpId", column = @Column(name = "ewEmpID", nullable = false)),
            @AttributeOverride(name = "ewProjNo", column = @Column(name = "ewProjNo", nullable = false)),
            @AttributeOverride(name = "ewWpNo", column = @Column(name = "ewWpNo", nullable = false, length = 8)) })
    public EmpwpId getId() {
        return this.id;
    }

    public void setId(EmpwpId id) {
        this.id = id;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "ewAssDt", nullable = false, length = 19)
    public Date getEwAssDt() {
        return this.ewAssDt;
    }

    public void setEwAssDt(Date ewAssDt) {
        this.ewAssDt = ewAssDt;
    }

    @Column(name = "ewEstHrs", precision = 5)
    public BigDecimal getEwEstHrs() {
        return this.ewEstHrs;
    }

    public void setEwEstHrs(BigDecimal ewEstHrs) {
        this.ewEstHrs = ewEstHrs;
    }

    @Column(name = "ewDel", nullable = false)
    public short getEwDel() {
        return this.ewDel;
    }

    public void setEwDel(short ewDel) {
        this.ewDel = ewDel;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "ewInsDt", nullable = false, length = 19)
    public Date getEwInsDt() {
        return this.ewInsDt;
    }

    public void setEwInsDt(Date ewInsDt) {
        this.ewInsDt = ewInsDt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "ewUpDt", nullable = false, length = 19)
    public Date getEwUpDt() {
        return this.ewUpDt;
    }

    public void setEwUpDt(Date ewUpDt) {
        this.ewUpDt = ewUpDt;
    }

}