package model;
// Generated 15-Feb-2017 2:38:53 PM by Hibernate Tools 3.5.0.Final

import java.util.Date;
import java.util.Set;
import java.util.SortedSet;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Project generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "Project")
public class Project implements java.io.Serializable {

    /**
     * Project number.
     */
    private Integer projNo;
    
    /**
     * Project name.
     */
    private String projNm;
    
    /**
     * Project description.
     */
    private String projDesc;
    
    /**
     * Project manager.
     */
    private Integer projMan;
    
    /**
     * Project start date.
     */
    private Date projStaDt;
    
    /**
     * Project end date.
     */
    private Date projEndDt;
    
    /**
     * Project status.
     */
    private short projStatus;
    
    /**
     * Project deleted flag.
     */
    private short projDel;
    
    /**
     * Insert date.
     */
    private Date projInsDt;
    
    /**
     * Update date.
     */
    private Date projUdDt;

    public Project() {
    }

    public Project(String projNm, int projMan, short projStatus, short projDel, Date projInsDt, Date projUdDt) {
        this.projNm = projNm;
        this.projMan = projMan;
        this.projStatus = projStatus;
        this.projDel = projDel;
        this.projInsDt = projInsDt;
        this.projUdDt = projUdDt;
    }

    public Project(String projNm, String projDesc, int projMan, Date projStaDt, Date projEndDt, short projStatus,
            short projDel, Date projInsDt, Date projUdDt) {
        this.projNm = projNm;
        this.projDesc = projDesc;
        this.projMan = projMan;
        this.projStaDt = projStaDt;
        this.projEndDt = projEndDt;
        this.projStatus = projStatus;
        this.projDel = projDel;
        this.projInsDt = projInsDt;
        this.projUdDt = projUdDt;
    }
    
    private SortedSet<Workpack> workPackages;
    
    @OneToMany(fetch=FetchType.EAGER, cascade=CascadeType.MERGE)
    @JoinColumn(name="wpProjNo", referencedColumnName="projNo")
    @OrderBy("id.wpNo ASC")
    public SortedSet<Workpack> getWorkPackages() {
    	return this.workPackages;
    }
    
    public void setWorkPackages(SortedSet<Workpack> workpackages) {
    	this.workPackages = workpackages;
    }
    
    private Set<Employee> employees;
    
    @ManyToMany(mappedBy="projects", fetch=FetchType.EAGER)
    public Set<Employee> getEmployees() {
    	return this.employees;
    }
    
    public void setEmployees(Set<Employee> employees) {
    	this.employees = employees;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "projNo", unique = true, nullable = false)
    public Integer getProjNo() {
        return this.projNo;
    }

    public void setProjNo(Integer projNo) {
        this.projNo = projNo;
    }

    @Column(name = "projNm", nullable = false, length = 64)
    public String getProjNm() {
        return this.projNm;
    }

    public void setProjNm(String projNm) {
        this.projNm = projNm;
    }

    @Column(name = "projDesc")
    public String getProjDesc() {
        return this.projDesc;
    }

    public void setProjDesc(String projDesc) {
        this.projDesc = projDesc;
    }

    @Column(name = "projMan")
    public Integer getProjMan() {
        return this.projMan;
    }

    public void setProjMan(Integer projMan) {
        this.projMan = projMan;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "projStaDt", length = 10)
    public Date getProjStaDt() {
        return this.projStaDt;
    }

    public void setProjStaDt(Date projStaDt) {
        this.projStaDt = projStaDt;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "projEndDt", length = 10)
    public Date getProjEndDt() {
        return this.projEndDt;
    }

    public void setProjEndDt(Date projEndDt) {
        this.projEndDt = projEndDt;
    }

    @Column(name = "projStatus", nullable = false)
    public short getProjStatus() {
        return this.projStatus;
    }

    public void setProjStatus(short projStatus) {
        this.projStatus = projStatus;
    }

    @Column(name = "projDel", nullable = false)
    public short getProjDel() {
        return this.projDel;
    }

    public void setProjDel(short projDel) {
        this.projDel = projDel;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "projInsDt", nullable = false, length = 19)
    public Date getProjInsDt() {
        return this.projInsDt;
    }

    public void setProjInsDt(Date projInsDt) {
        this.projInsDt = projInsDt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "projUdDt", nullable = false, length = 19)
    public Date getProjUdDt() {
        return this.projUdDt;
    }

    public void setProjUdDt(Date projUdDt) {
        this.projUdDt = projUdDt;
    }
    
    public String toString() {
    	return this.projNo.toString();
    }

    /* =========================================== */
    public boolean equals(Object entityObject) {
        Project entity = (Project) entityObject;
        return this.getProjNo().equals(entity.getProjNo());
    }
    
}
