package model;
// Generated 15-Feb-2017 2:38:53 PM by Hibernate Tools 3.5.0.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.Set;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * Timesheet generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "Timesheet")
public class Timesheet implements java.io.Serializable {

    /**
     * Timesheet id.
     */
    private TimesheetId id;
    
    /**
     * Total hours on timesheet.
     */
    private BigDecimal tsTotal;
    
    /**
     * Overtime on timesheet.
     */
    private BigDecimal tsOverTm;
    
    /**
     * Flextime on timesheet.
     */
    private BigDecimal tsFlexTm;
    
    /**
     * Date that timesheet is signed.
     */
    private Date tsSignDt;
    
    /**
     * Timesheet submit flag.
     */
    private Short tsSubmit;
    
    /**
     * Labour grade of employee at time of timesheet.
     */
    private Labgrd tsPayGrade;
    
    /**
     * Date timesheet was approved.
     */
    private Date tsApprDt;
    
    /**
     * Timesheet approver id.
     */
    private Integer tsApprId;
    
    /**
     * Timesheet delete flag.
     */
    private short tsDel;
    
    /**
     * Insert date.
     */
    private Date tsInsDt;
    
    /**
     * Update date.
     */
    private Date tsUpDt;
    
    /**
     * If timesheet has been approved.
     */
    private Boolean isApprove;

    /**
     * Employee that this timesheet is for.
     */
    private Employee employee;
    
    /**
     * Timesheet approver.
     */
    private Employee tsApprover;
    
    /**
     * Rows in this timesheet.
     */
    private Set<Tsrow> tsrow;
    /* ============================================== */
    /**
     * Get isApprove.
     * @return isApprove
     */
    @Transient
    public Boolean getIsApprove() {
        return isApprove;
    }

    /**
     * Set isApprove.
     * @param isApprove isApprove
     */
    public void setIsApprove(Boolean isApprove) {
        this.isApprove = isApprove;
    }
    /* ============================================== */
    /**
     * Get employee.
     * @return employee
     */
    @ManyToOne
    @JoinColumn(name = "tsEmpId", insertable = false, updatable = false)
    public Employee getEmployee() {
        return employee;
    }

    /**
     * Set employee.
     * @param employee employee
     */
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }

    /**
     * Get tsApprover.
     * @return tsApprover
     */
    @ManyToOne(optional = false)
    @JoinColumn(name = "tsApprID", referencedColumnName="empId")
    public Employee getTsApprover() {
        return tsApprover;
    }

    /**
     * Set tsApprover.
     * @param tsApprover tsApprover
     */
    public void setTsApprover(Employee tsApprover) {
        this.tsApprover = tsApprover;
    }

    /**
     * Get tsrow.
     * @return tsrow
     */
    @OneToMany(mappedBy = "timesheet", fetch = FetchType.EAGER)
    public Set<Tsrow> getTsrow() {
        return tsrow;
    }

    /**
     * Set tsrow.
     * @param tsrow tsrow
     */
    public void setTsrow(Set<Tsrow> tsrow) {
        this.tsrow = tsrow;
    }

    /**
     * Default ctor.
     */
    public Timesheet() {
    }

    /**
     * Create a timesheet.
     * @param id timesheet id.
     * @param tsDel delete flag
     * @param tsInsDt insert date
     * @param tsUpDt update date
     */
    public Timesheet(TimesheetId id, short tsDel, Date tsInsDt, Date tsUpDt) {
        this.id = id;
        this.tsDel = tsDel;
        this.tsInsDt = tsInsDt;
        this.tsUpDt = tsUpDt;
    }

    /**
     * Create a timesheet.
     * @param id timesheet id.
     * @param tsTotal total hours
     * @param tsOverTm overtime
     * @param tsFlexTm flextime
     * @param tsSignDt sign date
     * @param tsSubmit submit flag
     * @param tsApprDt approve date
     * @param tsApprId approver id
     * @param tsDel delete flag
     * @param tsInsDt insert date
     * @param tsUpDt update date
     */
    public Timesheet(TimesheetId id, BigDecimal tsTotal, BigDecimal tsOverTm, BigDecimal tsFlexTm, Date tsSignDt,
            Short tsSubmit, Date tsApprDt, Integer tsApprId, short tsDel, Date tsInsDt, Date tsUpDt) {
        this.id = id;
        this.tsTotal = tsTotal;
        this.tsOverTm = tsOverTm;
        this.tsFlexTm = tsFlexTm;
        this.tsSignDt = tsSignDt;
        this.tsSubmit = tsSubmit;
        this.tsApprDt = tsApprDt;
        this.tsApprId = tsApprId;
        this.tsDel = tsDel;
        this.tsInsDt = tsInsDt;
        this.tsUpDt = tsUpDt;
    }

    /**
     * Get id.
     * @return id
     */
    @EmbeddedId
    @AttributeOverrides({ @AttributeOverride(name = "tsEmpId", column = @Column(name = "tsEmpID", nullable = false)),
            @AttributeOverride(name = "tsWkEnd", column = @Column(name = "tsWkEnd", nullable = false, length = 8)) })
    public TimesheetId getId() {
        return this.id;
    }

    /**
     * Set id.
     * @param id id
     */
    public void setId(TimesheetId id) {
        this.id = id;
    }

    /**
     * Get tsTotal.
     * @return tsTotal
     */
    @Column(name = "tsTotal", precision = 5)
    public BigDecimal getTsTotal() {
        return this.tsTotal;
    }

    /**
     * Set tsTotal. 
     * @param tsTotal tsTotal
     */
    public void setTsTotal(BigDecimal tsTotal) {
        this.tsTotal = tsTotal;
    }

    /**
     * Get tsOverTm.
     * @return tsOverTm
     */
    @Column(name = "tsOverTm", precision = 4)
    public BigDecimal getTsOverTm() {
        return this.tsOverTm;
    }

    /**
     * Set tsOverTm.
     * @param tsOverTm tsOverTm
     */
    public void setTsOverTm(BigDecimal tsOverTm) {
        this.tsOverTm = tsOverTm;
    }

    /**
     * Get tsFlexTm.
     * @return tsFlexTm
     */
    @Column(name = "tsFlexTm", precision = 4)
    public BigDecimal getTsFlexTm() {
        return this.tsFlexTm;
    }

    /**
     * Set tsFlexTm.
     * @param tsFlexTm tsFlexTm
     */
    public void setTsFlexTm(BigDecimal tsFlexTm) {
        this.tsFlexTm = tsFlexTm;
    }

    /**
     * Get tsSignDt.
     * @return tsSignDt
     */
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "tsSignDt", length = 19)
    public Date getTsSignDt() {
        return this.tsSignDt;
    }

    /**
     * Set tsSignDt.
     * @param tsSignDt tsSignDt
     */
    public void setTsSignDt(Date tsSignDt) {
        this.tsSignDt = tsSignDt;
    }

    /**
     * Get tsSubmit.
     * @return tsSubmit
     */
    @Column(name = "tsSubmit")
    public Short getTsSubmit() {
        return this.tsSubmit;
    }

    /**
     * Set tsSubmit.
     * @param tsSubmit tsSubmit
     */
    public void setTsSubmit(Short tsSubmit) {
        this.tsSubmit = tsSubmit;
    }

    /**
     * Get tsPayGrade.
     * @return tsPayGrade
     */
    @ManyToOne
    @JoinColumn(name = "tsPayGrade")
    public Labgrd getTsPayGrade() {
        return tsPayGrade;
    }

    /**
     * Set tsPayGrade.
     * @param tsPayGrade tsPayGrade
     */
    public void setTsPayGrade(Labgrd tsPayGrade) {
        this.tsPayGrade = tsPayGrade;
    }

    /**
     * Get tsApprDt.
     * @return tsApprDt
     */
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "tsApprDt", length = 19)
    public Date getTsApprDt() {
        return this.tsApprDt;
    }

    /**
     * Set tsApprDt.
     * @param tsApprDt tsApprDt
     */
    public void setTsApprDt(Date tsApprDt) {
        this.tsApprDt = tsApprDt;
    }

    /**
     * Get tsApprId.
     * @return tsApprId
     */
    @Column(name = "tsApprID", insertable = false, updatable = false)
    public Integer getTsApprId() {
        return this.tsApprId;
    }

    /**
     * Set tsApprId.
     * @param tsApprId tsApprId
     */
    public void setTsApprId(Integer tsApprId) {
        this.tsApprId = tsApprId;
    }

    /**
     * Get tsDel.
     * @return tsDel
     */
    @Column(name = "tsDel", nullable = false)
    public short getTsDel() {
        return this.tsDel;
    }

    /**
     * Set tsDel.
     * @param tsDel tsDel
     */
    public void setTsDel(short tsDel) {
        this.tsDel = tsDel;
    }

    /**
     * Get tsInsDt. 
     * @return tsInsDt
     */
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "tsInsDt", length = 19, insertable = false)
    public Date getTsInsDt() {
        return this.tsInsDt;
    }

    /**
     * Set tsInsDt.
     * @param tsInsDt tsInsDt
     */
    public void setTsInsDt(Date tsInsDt) {
        this.tsInsDt = tsInsDt;
    }

    /**
     * Get tsUpDt.
     * @return tsUpDt
     */
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "tsUpDt", length = 19, insertable = false)
    public Date getTsUpDt() {
        return this.tsUpDt;
    }

    /**
     * Set tsUpDt.
     * @param tsUpDt tsUpDt
     */
    public void setTsUpDt(Date tsUpDt) {
        this.tsUpDt = tsUpDt;
    }
}
