package model;
// Generated 15-Feb-2017 2:38:53 PM by Hibernate Tools 3.5.0.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.Set;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * Timesheet generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "Timesheet")
public class Timesheet implements java.io.Serializable {

    private TimesheetId id;
    
    /**
     * Total hours on timesheet.
     */
    private BigDecimal tsTotal;
    
    /**
     * Overtime on timesheet.
     */
    private BigDecimal tsOverTm;
    
    /**
     * Flextime on timesheet.
     */
    private BigDecimal tsFlexTm;
    
    /**
     * Date that timesheet is signed.
     */
    private Date tsSignDt;
    
    /**
     * Timesheet submit flag.
     */
    private Short tsSubmit;
    
    /**
     * Labour grade of employee at time of timesheet.
     */
    private Labgrd tsPayGrade;
    
    /**
     * Date timesheet was approved.
     */
    private Date tsApprDt;
    
    /**
     * Timesheet approver id.
     */
    private Integer tsApprId;
    
    /**
     * Timesheet delete flag.
     */
    private short tsDel;
    
    /**
     * Insert date.
     */
    private Date tsInsDt;
    
    /**
     * Update date.
     */
    private Date tsUpDt;
    
    /**
     * If timesheet has been approved.
     */
    private Boolean isApprove;

    /**
     * Employee that this timesheet is for.
     */
    private Employee employee;
    
    /**
     * Timesheet approver.
     */
    private Employee tsApprover;
    /* ============================================== */
    @Transient
    public Boolean getIsApprove() {
        return isApprove;
    }

    public void setIsApprove(Boolean isApprove) {
        this.isApprove = isApprove;
    }
    /* ============================================== */
    @ManyToOne
    @JoinColumn(name = "tsEmpId", insertable = false, updatable = false)
    public Employee getEmployee() {
        return employee;
    }

    public void setEmployee(Employee employee) {
        this.employee = employee;
    }

    @ManyToOne(optional = false)
    @JoinColumn(name = "tsApprID", referencedColumnName="empId")
    public Employee getTsApprover() {
        return tsApprover;
    }

    public void setTsApprover(Employee tsApprover) {
        this.tsApprover = tsApprover;
    }

    private Set<Tsrow> tsrow;

    @OneToMany(mappedBy = "timesheet", fetch = FetchType.EAGER)
    public Set<Tsrow> getTsrow() {
        return tsrow;
    }

    public void setTsrow(Set<Tsrow> tsrow) {
        this.tsrow = tsrow;
    }

    public Timesheet() {
    }

    public Timesheet(TimesheetId id, short tsDel, Date tsInsDt, Date tsUpDt) {
        this.id = id;
        this.tsDel = tsDel;
        this.tsInsDt = tsInsDt;
        this.tsUpDt = tsUpDt;
    }

    public Timesheet(TimesheetId id, BigDecimal tsTotal, BigDecimal tsOverTm, BigDecimal tsFlexTm, Date tsSignDt,
            Short tsSubmit, Date tsApprDt, Integer tsApprId, short tsDel, Date tsInsDt, Date tsUpDt) {
        this.id = id;
        this.tsTotal = tsTotal;
        this.tsOverTm = tsOverTm;
        this.tsFlexTm = tsFlexTm;
        this.tsSignDt = tsSignDt;
        this.tsSubmit = tsSubmit;
        this.tsApprDt = tsApprDt;
        this.tsApprId = tsApprId;
        this.tsDel = tsDel;
        this.tsInsDt = tsInsDt;
        this.tsUpDt = tsUpDt;
    }

    @EmbeddedId
    @AttributeOverrides({ @AttributeOverride(name = "tsEmpId", column = @Column(name = "tsEmpID", nullable = false)),
            @AttributeOverride(name = "tsWkEnd", column = @Column(name = "tsWkEnd", nullable = false, length = 8)) })
    public TimesheetId getId() {
        return this.id;
    }

    public void setId(TimesheetId id) {
        this.id = id;
    }

    @Column(name = "tsTotal", precision = 5)
    public BigDecimal getTsTotal() {
        return this.tsTotal;
    }

    public void setTsTotal(BigDecimal tsTotal) {
        this.tsTotal = tsTotal;
    }

    @Column(name = "tsOverTm", precision = 4)
    public BigDecimal getTsOverTm() {
        return this.tsOverTm;
    }

    public void setTsOverTm(BigDecimal tsOverTm) {
        this.tsOverTm = tsOverTm;
    }

    @Column(name = "tsFlexTm", precision = 4)
    public BigDecimal getTsFlexTm() {
        return this.tsFlexTm;
    }

    public void setTsFlexTm(BigDecimal tsFlexTm) {
        this.tsFlexTm = tsFlexTm;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "tsSignDt", length = 19)
    public Date getTsSignDt() {
        return this.tsSignDt;
    }

    public void setTsSignDt(Date tsSignDt) {
        this.tsSignDt = tsSignDt;
    }

    @Column(name = "tsSubmit")
    public Short getTsSubmit() {
        return this.tsSubmit;
    }

    public void setTsSubmit(Short tsSubmit) {
        this.tsSubmit = tsSubmit;
    }

    @ManyToOne
    @JoinColumn(name = "tsPayGrade")
    public Labgrd getTsPayGrade() {
        return tsPayGrade;
    }

    public void setTsPayGrade(Labgrd tsPayGrade) {
        this.tsPayGrade = tsPayGrade;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "tsApprDt", length = 19)
    public Date getTsApprDt() {
        return this.tsApprDt;
    }

    public void setTsApprDt(Date tsApprDt) {
        this.tsApprDt = tsApprDt;
    }

    @Column(name = "tsApprID", insertable = false, updatable = false)
    public Integer getTsApprId() {
        return this.tsApprId;
    }

    public void setTsApprId(Integer tsApprId) {
        this.tsApprId = tsApprId;
    }

    @Column(name = "tsDel", nullable = false)
    public short getTsDel() {
        return this.tsDel;
    }

    public void setTsDel(short tsDel) {
        this.tsDel = tsDel;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "tsInsDt", length = 19, insertable = false)
    public Date getTsInsDt() {
        return this.tsInsDt;
    }

    public void setTsInsDt(Date tsInsDt) {
        this.tsInsDt = tsInsDt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "tsUpDt", length = 19, insertable = false)
    public Date getTsUpDt() {
        return this.tsUpDt;
    }

    public void setTsUpDt(Date tsUpDt) {
        this.tsUpDt = tsUpDt;
    }
}
