package model;
// Generated 15-Feb-2017 2:38:53 PM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TimesheetId generated by hbm2java
 */
@SuppressWarnings("serial")
@Embeddable
public class TimesheetId implements java.io.Serializable {

    /**
     * Employee Id.
     */
    private int tsEmpId;
    
    /**
     * Week end date of the timesheet.
     */
    private String tsWkEnd;

    /**
     * Default ctor.
     */
    public TimesheetId() {
    }

    /**
     * Create a timesheet id.
     * @param tsEmpId employee id
     * @param tsWkEnd week end string
     */
    public TimesheetId(int tsEmpId, String tsWkEnd) {
        this.tsEmpId = tsEmpId;
        this.tsWkEnd = tsWkEnd;
    }

    /**
     * Get tsEmpId.
     * @return tsEmpId
     */
    @Column(name = "tsEmpID", nullable = false)
    public int getTsEmpId() {
        return this.tsEmpId;
    }

    /**
     * Set tsEmpId.
     * @param tsEmpId tsEmpId
     */
    public void setTsEmpId(int tsEmpId) {
        this.tsEmpId = tsEmpId;
    }

    /**
     * Get tsWkEnd.
     * @return tsWkEnd
     */
    @Column(name = "tsWkEnd", nullable = false, length = 8)
    public String getTsWkEnd() {
        return this.tsWkEnd;
    }

    /**
     * Set tsWkEnd.
     * @param tsWkEnd tsWkEnd
     */
    public void setTsWkEnd(String tsWkEnd) {
        this.tsWkEnd = tsWkEnd;
    }

    public boolean equals(Object other) {
        if ((this == other)) {            
            return true;
        }
        if ((other == null)) {            
            return false;
        }
        if (!(other instanceof TimesheetId)) {            
            return false;
        }
        TimesheetId castOther = (TimesheetId) other;

        return (this.getTsEmpId() == castOther.getTsEmpId())
                && ((this.getTsWkEnd() == castOther.getTsWkEnd()) || (this.getTsWkEnd() != null
                        && castOther.getTsWkEnd() != null && this.getTsWkEnd().equals(castOther.getTsWkEnd())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getTsEmpId();
        result = 37 * result + (getTsWkEnd() == null ? 0 : this.getTsWkEnd().hashCode());
        return result;
    }

}
