package model;
// Generated 15-Feb-2017 2:38:53 PM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TimesheetId generated by hbm2java
 */
@Embeddable
public class TimesheetId implements java.io.Serializable {

    private int tsEmpId;
    private String tsWkEnd;

    public TimesheetId() {
    }

    public TimesheetId(int tsEmpId, String tsWkEnd) {
        this.tsEmpId = tsEmpId;
        this.tsWkEnd = tsWkEnd;
    }

    @Column(name = "tsEmpID", nullable = false)
    public int getTsEmpId() {
        return this.tsEmpId;
    }

    public void setTsEmpId(int tsEmpId) {
        this.tsEmpId = tsEmpId;
    }

    @Column(name = "tsWkEnd", nullable = false, length = 8)
    public String getTsWkEnd() {
        return this.tsWkEnd;
    }

    public void setTsWkEnd(String tsWkEnd) {
        this.tsWkEnd = tsWkEnd;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof TimesheetId))
            return false;
        TimesheetId castOther = (TimesheetId) other;

        return (this.getTsEmpId() == castOther.getTsEmpId())
                && ((this.getTsWkEnd() == castOther.getTsWkEnd()) || (this.getTsWkEnd() != null
                        && castOther.getTsWkEnd() != null && this.getTsWkEnd().equals(castOther.getTsWkEnd())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getTsEmpId();
        result = 37 * result + (getTsWkEnd() == null ? 0 : this.getTsWkEnd().hashCode());
        return result;
    }

}
