package model;
// Generated 15-Feb-2017 2:38:53 PM by Hibernate Tools 3.5.0.Final

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;



/**
 * Timesheet generated by hbm2java
 */
@Entity
@Table(name = "Timesheet")
@IdClass(TimesheetId.class)
public class Timesheet implements java.io.Serializable {

    /* ======================================================== */
    private List<Tsrow> details;
    /* ======================================================== */
    
    private int tsEmpId;
    
    private String tsWkEnd;
    
    private BigDecimal tsTotal;
    private BigDecimal tsOverTm;
    private BigDecimal tsFlexTm;
    private Date tsSignDt;
    private Short tsSubmit;
    private Date tsApprDt;
    private Integer tsApprId;
    private short tsDel;
    private Date tsInsDt;
    private Date tsUpDt;

    public Timesheet() {
    }

    public Timesheet(int tsEmpId ,String tsWkEnd, short tsDel, Date tsInsDt, Date tsUpDt) {
        this.tsEmpId = tsEmpId;
        this.tsWkEnd = tsWkEnd;
        this.tsDel = tsDel;
        this.tsInsDt = tsInsDt;
        this.tsUpDt = tsUpDt;
    }

    public Timesheet(int tsEmpId ,String tsWkEnd, BigDecimal tsTotal, BigDecimal tsOverTm, BigDecimal tsFlexTm, Date tsSignDt,
            Short tsSubmit, Date tsApprDt, Integer tsApprId, short tsDel, Date tsInsDt, Date tsUpDt) {
        this.tsEmpId = tsEmpId;
        this.tsWkEnd = tsWkEnd;
        this.tsTotal = tsTotal;
        this.tsOverTm = tsOverTm;
        this.tsFlexTm = tsFlexTm;
        this.tsSignDt = tsSignDt;
        this.tsSubmit = tsSubmit;
        this.tsApprDt = tsApprDt;
        this.tsApprId = tsApprId;
        this.tsDel = tsDel;
        this.tsInsDt = tsInsDt;
        this.tsUpDt = tsUpDt;
        
        details = new ArrayList<Tsrow>();
        
    }

    @Id
    @Column(name = "tsEmpId", nullable = false)
    public int getTsEmpId() {
        return tsEmpId;
    }

    public void setTsEmpId(int tsEmpId) {
        this.tsEmpId = tsEmpId;
    }

    @Id
    @Column(name = "tsEmpId", nullable = false, length = 8)
    public String getTsWkEnd() {
        return tsWkEnd;
    }

    public void setTsWkEnd(String tsWkEnd) {
        this.tsWkEnd = tsWkEnd;
    }

    @Column(name = "tsTotal", precision = 5)
    public BigDecimal getTsTotal() {
        return this.tsTotal;
    }


    public void setTsTotal(BigDecimal tsTotal) {
        this.tsTotal = tsTotal;
    }

    @Column(name = "tsOverTm", precision = 4)
    public BigDecimal getTsOverTm() {
        return this.tsOverTm;
    }

    public void setTsOverTm(BigDecimal tsOverTm) {
        this.tsOverTm = tsOverTm;
    }

    @Column(name = "tsFlexTm", precision = 4)
    public BigDecimal getTsFlexTm() {
        return this.tsFlexTm;
    }

    public void setTsFlexTm(BigDecimal tsFlexTm) {
        this.tsFlexTm = tsFlexTm;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "tsSignDt", length = 19)
    public Date getTsSignDt() {
        return this.tsSignDt;
    }

    public void setTsSignDt(Date tsSignDt) {
        this.tsSignDt = tsSignDt;
    }

    @Column(name = "tsSubmit")
    public Short getTsSubmit() {
        return this.tsSubmit;
    }

    public void setTsSubmit(Short tsSubmit) {
        this.tsSubmit = tsSubmit;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "tsApprDt", length = 19)
    public Date getTsApprDt() {
        return this.tsApprDt;
    }

    public void setTsApprDt(Date tsApprDt) {
        this.tsApprDt = tsApprDt;
    }

    @Column(name = "tsApprID")
    public Integer getTsApprId() {
        return this.tsApprId;
    }

    public void setTsApprId(Integer tsApprId) {
        this.tsApprId = tsApprId;
    }

    @Column(name = "tsDel", nullable = false)
    public short getTsDel() {
        return this.tsDel;
    }

    public void setTsDel(short tsDel) {
        this.tsDel = tsDel;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "tsInsDt", nullable = false, length = 19)
    public Date getTsInsDt() {
        return this.tsInsDt;
    }

    public void setTsInsDt(Date tsInsDt) {
        this.tsInsDt = tsInsDt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "tsUpDt", nullable = false, length = 19)
    public Date getTsUpDt() {
        return this.tsUpDt;
    }

    public void setTsUpDt(Date tsUpDt) {
        this.tsUpDt = tsUpDt;
    }

    
    /* ======================================================== */
    public void addRow() {
        details.add(new Tsrow());
    }
    
    public void deleteRow(final Tsrow rowToRemove) {
        details.remove(rowToRemove);
    }
    /* ======================================================== */

}
