package model;
// Generated 15-Feb-2017 2:38:53 PM by Hibernate Tools 3.5.0.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;

/**
 * Tsrow generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "Tsrow", uniqueConstraints = @UniqueConstraint(columnNames = { "tsrEmpID", "tsrWkEnd", "tsrProjNo",
        "tsrWpNo" }))
public class Tsrow implements java.io.Serializable {

    /**
     * If row is editable or not.
     */
    private boolean editable;

    /**
     * Total of the row.
     */
    private BigDecimal total;
    /* ====================================== */

    /**
     * Row id.
     */
    private Long tsr_id;
    /**
     * Employee id of owner of timesheet row.
     */
    private int tsrEmpId;

    /**
     * Week this timesheet row is for.
     */
    private String tsrWkEnd;

    /**
     * Project of timesheet row.
     */
    private int tsrProjNo;

    /**
     * Work package of timesheet row.
     */
    private String tsrWpNo;

    /**
     * Hours for Saturday.
     */
    private BigDecimal tsrSat;

    /**
     * Hours for Sunday.
     */
    private BigDecimal tsrSun;

    /**
     * Hours for Monday.
     */
    private BigDecimal tsrMon;

    /**
     * Hours for Tuesday.
     */
    private BigDecimal tsrTue;

    /**
     * Hours for Wednesday.
     */
    private BigDecimal tsrWed;

    /**
     * Hours for Thursday.
     */
    private BigDecimal tsrThu;

    /**
     * Hours for Friday.
     */
    private BigDecimal tsrFri;

    /**
     * Hours for overtime.
     */
    private BigDecimal tsrOt;

    /**
     * Notes column.
     */
    private String tsrNote;

    /**
     * Row deleted flag.
     */
    private short tsrDel;

    /**
     * Insert date.
     */
    private Date tsrInsDt;

    /**
     * Update date.
     */
    private Date tsrUpDt;

    /**
     * Timesheet this row is a part of.
     */
    private Timesheet timesheet;

    /**
     * Get timesheet.
     * 
     * @return timesheet
     */
    @ManyToOne
    @JoinColumns({ @JoinColumn(name = "tsrWkEnd", referencedColumnName = "tsWkEnd"),
            @JoinColumn(name = "tsrEmpID", referencedColumnName = "tsEmpID") })
    public Timesheet getTimesheet() {
        return timesheet;
    }

    /**
     * Set timesheet.
     * 
     * @param timesheet
     *            timesheet
     */
    public void setTimesheet(Timesheet timesheet) {
        this.timesheet = timesheet;
    }

    /**
     * Default ctor.
     */
    public Tsrow() {
        total = new BigDecimal(0);
    }

    /**
     * Create a tsrow.
     * 
     * @param tsrEmpId
     *            employee id
     * @param tsrWkEnd
     *            week end string
     * @param tsrProjNo
     *            project number
     * @param tsrWpNo
     *            wp number
     * @param tsrDel
     *            delete flag
     * @param tsrInsDt
     *            insert date
     * @param tsrUpDt
     *            update date
     */
    public Tsrow(int tsrEmpId, String tsrWkEnd, int tsrProjNo, String tsrWpNo, short tsrDel, Date tsrInsDt,
            Date tsrUpDt) {
        this.tsrEmpId = tsrEmpId;
        this.tsrWkEnd = tsrWkEnd;
        this.tsrProjNo = tsrProjNo;
        this.tsrWpNo = tsrWpNo;
        this.tsrDel = tsrDel;
        this.tsrInsDt = tsrInsDt;
        this.tsrUpDt = tsrUpDt;
    }

    /**
     * Create a Tsrow
     * 
     * @param tsrEmpId
     *            employee id
     * @param tsrWkEnd
     *            week end string
     * @param tsrProjNo
     *            project number
     * @param tsrWpNo
     *            wp number
     * @param tsrSat
     *            sat hours
     * @param tsrSun
     *            sun hours
     * @param tsrMon
     *            mon hours
     * @param tsrTue
     *            tue hours
     * @param tsrWed
     *            wed hours
     * @param tsrThu
     *            thu hours
     * @param tsrFri
     *            fri hours
     * @param tsrNote
     *            note
     * @param tsrDel
     *            delete flag
     * @param tsrInsDt
     *            insert date
     * @param tsrUpDt
     *            update date
     */
    public Tsrow(int tsrEmpId, String tsrWkEnd, int tsrProjNo, String tsrWpNo, BigDecimal tsrSat, BigDecimal tsrSun,
            BigDecimal tsrMon, BigDecimal tsrTue, BigDecimal tsrWed, BigDecimal tsrThu, BigDecimal tsrFri,
            String tsrNote, short tsrDel, Date tsrInsDt, Date tsrUpDt) {
        this.tsrEmpId = tsrEmpId;
        this.tsrWkEnd = tsrWkEnd;
        this.tsrProjNo = tsrProjNo;
        this.tsrWpNo = tsrWpNo;
        this.tsrSat = tsrSat;
        this.tsrSun = tsrSun;
        this.tsrMon = tsrMon;
        this.tsrTue = tsrTue;
        this.tsrWed = tsrWed;
        this.tsrThu = tsrThu;
        this.tsrFri = tsrFri;
        this.tsrNote = tsrNote;
        this.tsrDel = tsrDel;
        this.tsrInsDt = tsrInsDt;
        this.tsrUpDt = tsrUpDt;
    }

    /**
     * Get tsr_id.
     * 
     * @return tsr_id
     */
    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "tsr_id", unique = true, nullable = false)
    public Long getId() {
        return this.tsr_id;
    }

    /**
     * Set tsr_id.
     * 
     * @param id
     *            tsr_id
     */
    public void setId(Long id) {
        this.tsr_id = id;
    }

    /**
     * Get tsrEmpId.
     * 
     * @return tsrEmpId
     */
    @Column(name = "tsrEmpID", insertable = false, updatable = false, nullable = false)
    public int getTsrEmpId() {
        return this.tsrEmpId;
    }

    /**
     * Set tsrEmpId.
     * 
     * @param tsrEmpId
     *            tsrEmpId
     */
    public void setTsrEmpId(int tsrEmpId) {
        this.tsrEmpId = tsrEmpId;
    }

    /**
     * Get tsrWkEnd.
     * 
     * @return tsrWkEnd
     */
    @Column(name = "tsrWkEnd", insertable = false, updatable = false, nullable = false, length = 8)
    public String getTsrWkEnd() {
        return this.tsrWkEnd;
    }

    /**
     * Set tsrWkEnd.
     * 
     * @param tsrWkEnd
     *            tsrWkEnd
     */
    public void setTsrWkEnd(String tsrWkEnd) {
        this.tsrWkEnd = tsrWkEnd;
    }

    /**
     * Get tsrProjNo.
     * 
     * @return tsrProjNo
     */
    @Column(name = "tsrProjNo", nullable = false)
    public int getTsrProjNo() {
        return this.tsrProjNo;
    }

    /**
     * Set tsrProjNo.
     * 
     * @param tsrProjNo
     *            tsrProjNo
     */
    public void setTsrProjNo(int tsrProjNo) {
        this.tsrProjNo = tsrProjNo;
    }

    /**
     * Get tsrWpNo.
     * 
     * @return tsrWpNo
     */
    @Column(name = "tsrWpNo", nullable = false, length = 8)
    public String getTsrWpNo() {
        return this.tsrWpNo;
    }

    /**
     * Set tsrWpNo.
     * 
     * @param tsrWpNo
     *            tsrWpNo
     */
    public void setTsrWpNo(String tsrWpNo) {
        this.tsrWpNo = tsrWpNo;
    }

    /**
     * Get tsrSat.
     * 
     * @return tsrSat
     */
    @Column(name = "tsrSat", precision = 4)
    public BigDecimal getTsrSat() {
        return this.tsrSat;
    }

    /**
     * Set tsrSat.
     * 
     * @param tsrSat
     *            tsrSat
     */
    public void setTsrSat(BigDecimal tsrSat) {
        this.tsrSat = tsrSat;
    }

    /**
     * Get tsrSun.
     * 
     * @return tsrSun
     */
    @Column(name = "tsrSun", precision = 4)
    public BigDecimal getTsrSun() {
        return this.tsrSun;
    }

    /**
     * Set tsrSun.
     * 
     * @param tsrSun
     *            tsrSun
     */
    public void setTsrSun(BigDecimal tsrSun) {
        this.tsrSun = tsrSun;
    }

    /**
     * Get tsrMon.
     * 
     * @return tsrMon
     */
    @Column(name = "tsrMon", precision = 4)
    public BigDecimal getTsrMon() {
        return this.tsrMon;
    }

    /**
     * Set tsrMon.
     * 
     * @param tsrMon
     *            tsrMon
     */
    public void setTsrMon(BigDecimal tsrMon) {
        this.tsrMon = tsrMon;
    }

    /**
     * Get tsrTue.
     * 
     * @return tsrTue
     */
    @Column(name = "tsrTue", precision = 4)
    public BigDecimal getTsrTue() {
        return this.tsrTue;
    }

    /**
     * Set tsrTue.
     * 
     * @param tsrTue
     *            tsrTue
     */
    public void setTsrTue(BigDecimal tsrTue) {
        this.tsrTue = tsrTue;
    }

    /**
     * Get tsrWed.
     * 
     * @return tsrWed
     */
    @Column(name = "tsrWed", precision = 4)
    public BigDecimal getTsrWed() {
        return this.tsrWed;
    }

    /**
     * Set tsrWed.
     * 
     * @param tsrWed
     *            tsrWed
     */
    public void setTsrWed(BigDecimal tsrWed) {
        this.tsrWed = tsrWed;
    }

    /**
     * Get tsrThu.
     * 
     * @return tsrThu
     */
    @Column(name = "tsrThu", precision = 4)
    public BigDecimal getTsrThu() {
        return this.tsrThu;
    }

    /**
     * Set tsrThu.
     * 
     * @param tsrThu
     *            tsrThu
     */
    public void setTsrThu(BigDecimal tsrThu) {
        this.tsrThu = tsrThu;
    }

    /**
     * Get tsrFri.
     * 
     * @return tsrFri
     */
    @Column(name = "tsrFri", precision = 4)
    public BigDecimal getTsrFri() {
        return this.tsrFri;
    }

    /**
     * Set tsrFri.
     * 
     * @param tsrFri
     *            tsrFri
     */
    public void setTsrFri(BigDecimal tsrFri) {
        this.tsrFri = tsrFri;
    }

    /**
     * Get tsrOt.
     * 
     * @return tsrOt
     */
    @Column(name = "tsrOt", precision = 4)
    public BigDecimal getTsrOt() {
        return this.tsrOt;
    }

    /**
     * Set tsrOt.
     * 
     * @param tsrOt
     *            tsrOt
     */
    public void setTsrOt(BigDecimal tsrOt) {
        this.tsrOt = tsrOt;
    }

    /**
     * Get tsrNote.
     * 
     * @return tsrNote
     */
    @Column(name = "tsrNote")
    public String getTsrNote() {
        return this.tsrNote;
    }

    /**
     * Set tsrNote.
     * 
     * @param tsrNote
     *            tsrNote
     */
    public void setTsrNote(String tsrNote) {
        this.tsrNote = tsrNote;
    }

    /**
     * Get tsrDel.
     * 
     * @return tsrDel
     */
    @Column(name = "tsrDel", nullable = false)
    public short getTsrDel() {
        return this.tsrDel;
    }

    /**
     * Set tsrDel.
     * 
     * @param tsrDel
     *            tsrDel
     */
    public void setTsrDel(short tsrDel) {
        this.tsrDel = tsrDel;
    }

    /**
     * Get tsrInsDt.
     * 
     * @return tsrInsDt
     */
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "tsrInsDt", insertable = false, updatable = false, nullable = false, length = 19)
    public Date getTsrInsDt() {
        return this.tsrInsDt;
    }

    /**
     * Set tsrInsDt.
     * 
     * @param tsrInsDt
     *            tsrInsDt
     */
    public void setTsrInsDt(Date tsrInsDt) {
        this.tsrInsDt = tsrInsDt;
    }

    /**
     * Get tsrUpDt.
     * 
     * @return tsrUpDt
     */
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "tsrUpDt", insertable = false, updatable = false, nullable = false, length = 19)
    public Date getTsrUpDt() {
        return this.tsrUpDt;
    }

    /**
     * Set tsrUpDt.
     * 
     * @param tsrUpDt
     *            tsrUpDt
     */
    public void setTsrUpDt(Date tsrUpDt) {
        this.tsrUpDt = tsrUpDt;
    }

    /* =============================================== */

    /**
     * Get editable.
     * 
     * @return editable
     */
    @Transient
    public boolean getEditable() {
        return editable;
    }

    /**
     * Set editable.
     * 
     * @param editable
     *            editable
     */
    public void setEditable(boolean editable) {
        this.editable = editable;
    }

    /**
     * Get total.
     * 
     * @return total.
     */
    @Transient
    public BigDecimal getTotal() {
        this.total = new BigDecimal(0);
        BigDecimal[] week = { this.tsrMon, this.tsrTue, this.tsrWed, this.tsrThu, this.tsrFri, this.tsrSat,
                this.tsrSun };
        for (int i = 0; i < week.length; i++) {
            if (week[i] != null) {
                this.total = this.total.add(new BigDecimal(week[i].doubleValue()));
            }
        }
        return total;
    }

    /**
     * Set total.
     * 
     * @param total
     *            total
     */
    public void setTotal(BigDecimal total) {
        this.total = total;
    }

    public boolean equals(Object entityObject) {
        Tsrow entity = (Tsrow) entityObject;
        return this.getTsrWpNo().equals(entity.getTsrWpNo()) && this.getTsrProjNo() == entity.getTsrProjNo();
    }

}