package model;
// Generated 15-Feb-2017 2:38:53 PM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * WorkpackId generated by hbm2java
 */
@SuppressWarnings("serial")
@Embeddable
public class WorkpackId implements java.io.Serializable {

    /**
     * Project number.
     */
    private int wpProjNo;
    
    /**
     * Work package number.
     */
    private String wpNo;

    public WorkpackId() {
    }

    public WorkpackId(int wpProjNo, String wpNo) {
        this.wpProjNo = wpProjNo;
        this.wpNo = wpNo;
    }

    @Column(name = "wpProjNo", nullable = false)
    public int getWpProjNo() {
        return this.wpProjNo;
    }

    public void setWpProjNo(int wpProjNo) {
        this.wpProjNo = wpProjNo;
    }

    @Column(name = "wpNo", nullable = false, length = 8)
    public String getWpNo() {
        return this.wpNo;
    }

    public void setWpNo(String wpNo) {
        this.wpNo = wpNo;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof WorkpackId))
            return false;
        WorkpackId castOther = (WorkpackId) other;

        return (this.getWpProjNo() == castOther.getWpProjNo())
                && ((this.getWpNo() == castOther.getWpNo()) || (this.getWpNo() != null && castOther.getWpNo() != null
                        && this.getWpNo().equals(castOther.getWpNo())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getWpProjNo();
        result = 37 * result + (getWpNo() == null ? 0 : this.getWpNo().hashCode());
        return result;
    }

}
