package model;
// Generated 15-Feb-2017 2:38:53 PM by Hibernate Tools 3.5.0.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Workpack generated by hbm2java
 */
@Entity
@Table(name = "Workpack")
public class Workpack implements java.io.Serializable {

    private WorkpackId id;
    private String wpNm;
    private String wpDesc;
    private Integer wpResEng;
    private short wpLowLev;
    private String wpParent;
    private Short wpStatus;
    private Date wpStaDt;
    private Date wpEndDt;
    private BigDecimal wpPlanPh;
    private BigDecimal wpBudget;
    private BigDecimal wpActCost;
    private BigDecimal wpProgHrs;
    private short wpDel;
    private Date wpInsDt;
    private Date wpUpDt;

    public Workpack() {
    }

    public Workpack(WorkpackId id, String wpNm, short wpLowLev, short wpDel, Date wpInsDt, Date wpUpDt) {
        this.id = id;
        this.wpNm = wpNm;
        this.wpLowLev = wpLowLev;
        this.wpDel = wpDel;
        this.wpInsDt = wpInsDt;
        this.wpUpDt = wpUpDt;
    }

    public Workpack(WorkpackId id, String wpNm, String wpDesc, Integer wpResEng, short wpLowLev, String wpParent,
            Short wpStatus, Date wpStaDt, Date wpEndDt, BigDecimal wpPlanPh, BigDecimal wpBudget, BigDecimal wpActCost,
            BigDecimal wpProgHrs, short wpDel, Date wpInsDt, Date wpUpDt) {
        this.id = id;
        this.wpNm = wpNm;
        this.wpDesc = wpDesc;
        this.wpResEng = wpResEng;
        this.wpLowLev = wpLowLev;
        this.wpParent = wpParent;
        this.wpStatus = wpStatus;
        this.wpStaDt = wpStaDt;
        this.wpEndDt = wpEndDt;
        this.wpPlanPh = wpPlanPh;
        this.wpBudget = wpBudget;
        this.wpActCost = wpActCost;
        this.wpProgHrs = wpProgHrs;
        this.wpDel = wpDel;
        this.wpInsDt = wpInsDt;
        this.wpUpDt = wpUpDt;
    }

    @EmbeddedId

    @AttributeOverrides({ @AttributeOverride(name = "wpProjNo", column = @Column(name = "wpProjNo", nullable = false)),
            @AttributeOverride(name = "wpNo", column = @Column(name = "wpNo", nullable = false, length = 8)) })
    public WorkpackId getId() {
        return this.id;
    }

    public void setId(WorkpackId id) {
        this.id = id;
    }

    @Column(name = "wpNm", nullable = false, length = 64)
    public String getWpNm() {
        return this.wpNm;
    }

    public void setWpNm(String wpNm) {
        this.wpNm = wpNm;
    }

    @Column(name = "wpDesc")
    public String getWpDesc() {
        return this.wpDesc;
    }

    public void setWpDesc(String wpDesc) {
        this.wpDesc = wpDesc;
    }

    @Column(name = "wpResEng")
    public Integer getWpResEng() {
        return this.wpResEng;
    }

    public void setWpResEng(Integer wpResEng) {
        this.wpResEng = wpResEng;
    }

    @Column(name = "wpLowLev", nullable = false)
    public short getWpLowLev() {
        return this.wpLowLev;
    }

    public void setWpLowLev(short wpLowLev) {
        this.wpLowLev = wpLowLev;
    }

    @Column(name = "wpParent", length = 8)
    public String getWpParent() {
        return this.wpParent;
    }

    public void setWpParent(String wpParent) {
        this.wpParent = wpParent;
    }

    @Column(name = "wpStatus")
    public Short getWpStatus() {
        return this.wpStatus;
    }

    public void setWpStatus(Short wpStatus) {
        this.wpStatus = wpStatus;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "wpStaDt", length = 10)
    public Date getWpStaDt() {
        return this.wpStaDt;
    }

    public void setWpStaDt(Date wpStaDt) {
        this.wpStaDt = wpStaDt;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "wpEndDt", length = 10)
    public Date getWpEndDt() {
        return this.wpEndDt;
    }

    public void setWpEndDt(Date wpEndDt) {
        this.wpEndDt = wpEndDt;
    }

    @Column(name = "wpPlanPH", precision = 6)
    public BigDecimal getWpPlanPh() {
        return this.wpPlanPh;
    }

    public void setWpPlanPh(BigDecimal wpPlanPh) {
        this.wpPlanPh = wpPlanPh;
    }

    @Column(name = "wpBudget", precision = 10)
    public BigDecimal getWpBudget() {
        return this.wpBudget;
    }

    public void setWpBudget(BigDecimal wpBudget) {
        this.wpBudget = wpBudget;
    }

    @Column(name = "wpActCost", precision = 10)
    public BigDecimal getWpActCost() {
        return this.wpActCost;
    }

    public void setWpActCost(BigDecimal wpActCost) {
        this.wpActCost = wpActCost;
    }

    @Column(name = "wpProgHrs", precision = 5)
    public BigDecimal getWpProgHrs() {
        return this.wpProgHrs;
    }

    public void setWpProgHrs(BigDecimal wpProgHrs) {
        this.wpProgHrs = wpProgHrs;
    }

    @Column(name = "wpDel", nullable = false)
    public short getWpDel() {
        return this.wpDel;
    }

    public void setWpDel(short wpDel) {
        this.wpDel = wpDel;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "wpInsDt", nullable = false, length = 19)
    public Date getWpInsDt() {
        return this.wpInsDt;
    }

    public void setWpInsDt(Date wpInsDt) {
        this.wpInsDt = wpInsDt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "wpUpDt", nullable = false, length = 19)
    public Date getWpUpDt() {
        return this.wpUpDt;
    }

    public void setWpUpDt(Date wpUpDt) {
        this.wpUpDt = wpUpDt;
    }

}