package model;
// Generated 15-Feb-2017 2:38:53 PM by Hibernate Tools 3.5.0.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Wpstarep generated by hbm2java
 */
@Entity
@Table(name = "Wpstarep")
public class Wpstarep implements java.io.Serializable {

    private WpstarepId id;
    private Date wsrRepDt;
    private Integer wsrWriter;
    private BigDecimal wsrProgLw;
    private String wsrProbLw;
    private BigDecimal wsrProgNw;
    private String wsrProbNw;
    private BigDecimal wsrEstWr;
    private short wsrSubmit;
    private Date wsrApprDt;
    private Integer wsrApprId;
    private short wsrDel;
    private Date wsrInsDt;
    private Date wsrUpDt;

    public Wpstarep() {
    }

    public Wpstarep(WpstarepId id, short wsrSubmit, short wsrDel, Date wsrInsDt, Date wsrUpDt) {
        this.id = id;
        this.wsrSubmit = wsrSubmit;
        this.wsrDel = wsrDel;
        this.wsrInsDt = wsrInsDt;
        this.wsrUpDt = wsrUpDt;
    }

    public Wpstarep(WpstarepId id, Date wsrRepDt, Integer wsrWriter, BigDecimal wsrProgLw, String wsrProbLw,
            BigDecimal wsrProgNw, String wsrProbNw, BigDecimal wsrEstWr, short wsrSubmit, Date wsrApprDt,
            Integer wsrApprId, short wsrDel, Date wsrInsDt, Date wsrUpDt) {
        this.id = id;
        this.wsrRepDt = wsrRepDt;
        this.wsrWriter = wsrWriter;
        this.wsrProgLw = wsrProgLw;
        this.wsrProbLw = wsrProbLw;
        this.wsrProgNw = wsrProgNw;
        this.wsrProbNw = wsrProbNw;
        this.wsrEstWr = wsrEstWr;
        this.wsrSubmit = wsrSubmit;
        this.wsrApprDt = wsrApprDt;
        this.wsrApprId = wsrApprId;
        this.wsrDel = wsrDel;
        this.wsrInsDt = wsrInsDt;
        this.wsrUpDt = wsrUpDt;
    }

    @EmbeddedId

    @AttributeOverrides({
            @AttributeOverride(name = "wsrProjNo", column = @Column(name = "wsrProjNo", nullable = false)),
            @AttributeOverride(name = "wsrWpNo", column = @Column(name = "wsrWpNo", nullable = false, length = 8)) })
    public WpstarepId getId() {
        return this.id;
    }

    public void setId(WpstarepId id) {
        this.id = id;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "wsrRepDt", length = 19)
    public Date getWsrRepDt() {
        return this.wsrRepDt;
    }

    public void setWsrRepDt(Date wsrRepDt) {
        this.wsrRepDt = wsrRepDt;
    }

    @Column(name = "wsrWriter")
    public Integer getWsrWriter() {
        return this.wsrWriter;
    }

    public void setWsrWriter(Integer wsrWriter) {
        this.wsrWriter = wsrWriter;
    }

    @Column(name = "wsrProgLW", precision = 5)
    public BigDecimal getWsrProgLw() {
        return this.wsrProgLw;
    }

    public void setWsrProgLw(BigDecimal wsrProgLw) {
        this.wsrProgLw = wsrProgLw;
    }

    @Column(name = "wsrProbLW")
    public String getWsrProbLw() {
        return this.wsrProbLw;
    }

    public void setWsrProbLw(String wsrProbLw) {
        this.wsrProbLw = wsrProbLw;
    }

    @Column(name = "wsrProgNW", precision = 5)
    public BigDecimal getWsrProgNw() {
        return this.wsrProgNw;
    }

    public void setWsrProgNw(BigDecimal wsrProgNw) {
        this.wsrProgNw = wsrProgNw;
    }

    @Column(name = "wsrProbNW")
    public String getWsrProbNw() {
        return this.wsrProbNw;
    }

    public void setWsrProbNw(String wsrProbNw) {
        this.wsrProbNw = wsrProbNw;
    }

    @Column(name = "wsrEstWR", precision = 5)
    public BigDecimal getWsrEstWr() {
        return this.wsrEstWr;
    }

    public void setWsrEstWr(BigDecimal wsrEstWr) {
        this.wsrEstWr = wsrEstWr;
    }

    @Column(name = "wsrSubmit", nullable = false)
    public short getWsrSubmit() {
        return this.wsrSubmit;
    }

    public void setWsrSubmit(short wsrSubmit) {
        this.wsrSubmit = wsrSubmit;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "wsrApprDt", length = 19)
    public Date getWsrApprDt() {
        return this.wsrApprDt;
    }

    public void setWsrApprDt(Date wsrApprDt) {
        this.wsrApprDt = wsrApprDt;
    }

    @Column(name = "wsrApprID")
    public Integer getWsrApprId() {
        return this.wsrApprId;
    }

    public void setWsrApprId(Integer wsrApprId) {
        this.wsrApprId = wsrApprId;
    }

    @Column(name = "wsrDel", nullable = false)
    public short getWsrDel() {
        return this.wsrDel;
    }

    public void setWsrDel(short wsrDel) {
        this.wsrDel = wsrDel;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "wsrInsDt", nullable = false, length = 19)
    public Date getWsrInsDt() {
        return this.wsrInsDt;
    }

    public void setWsrInsDt(Date wsrInsDt) {
        this.wsrInsDt = wsrInsDt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "wsrUpDt", nullable = false, length = 19)
    public Date getWsrUpDt() {
        return this.wsrUpDt;
    }

    public void setWsrUpDt(Date wsrUpDt) {
        this.wsrUpDt = wsrUpDt;
    }

}
