package model;
// Generated 15-Feb-2017 2:38:53 PM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * WpstarepId generated by hbm2java
 */
@Embeddable
public class WpstarepId implements java.io.Serializable {

    private int wsrProjNo;
    private String wsrWpNo;

    public WpstarepId() {
    }

    public WpstarepId(int wsrProjNo, String wsrWpNo) {
        this.wsrProjNo = wsrProjNo;
        this.wsrWpNo = wsrWpNo;
    }

    @Column(name = "wsrProjNo", nullable = false)
    public int getWsrProjNo() {
        return this.wsrProjNo;
    }

    public void setWsrProjNo(int wsrProjNo) {
        this.wsrProjNo = wsrProjNo;
    }

    @Column(name = "wsrWpNo", nullable = false, length = 8)
    public String getWsrWpNo() {
        return this.wsrWpNo;
    }

    public void setWsrWpNo(String wsrWpNo) {
        this.wsrWpNo = wsrWpNo;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof WpstarepId))
            return false;
        WpstarepId castOther = (WpstarepId) other;

        return (this.getWsrProjNo() == castOther.getWsrProjNo())
                && ((this.getWsrWpNo() == castOther.getWsrWpNo()) || (this.getWsrWpNo() != null
                        && castOther.getWsrWpNo() != null && this.getWsrWpNo().equals(castOther.getWsrWpNo())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getWsrProjNo();
        result = 37 * result + (getWsrWpNo() == null ? 0 : this.getWsrWpNo().hashCode());
        return result;
    }

}
