package model;
// Generated 15-Feb-2017 2:38:53 PM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * WpstarepId generated by hbm2java
 */
@SuppressWarnings("serial")
@Embeddable
public class WpstarepId implements java.io.Serializable {

    /**
     * Project number.
     */
    private int wsrProjNo;
    
    /**
     * Work package number.
     */
    private String wsrWpNo;
    
    /**
     * Report date.
     */
    private String wsrRepDt;

    /**
     * Default ctor.
     */
    public WpstarepId() {
    }

    /**
     * Create a wpstarepid
     * @param wsrProjNo project number
     * @param wsrWpNo wp number
     * @param wsrRepDt report date
     */
    public WpstarepId(int wsrProjNo, String wsrWpNo, String wsrRepDt) {
        this.wsrProjNo = wsrProjNo;
        this.wsrWpNo = wsrWpNo;
        this.wsrRepDt = wsrRepDt;
    }

    /**
     * Get wsrProjNo. 
     * @return wsrProjNo
     */
    @Column(name = "wsrProjNo", nullable = false)
    public int getWsrProjNo() {
        return this.wsrProjNo;
    }

    /**
     * Set wsrProjNo.
     * @param wsrProjNo wsrProjNo
     */
    public void setWsrProjNo(int wsrProjNo) {
        this.wsrProjNo = wsrProjNo;
    }

    /**
     * Get wsrWpNo.
     * @return wsrWpNo
     */
    @Column(name = "wsrWpNo", nullable = false, length = 8)
    public String getWsrWpNo() {
        return this.wsrWpNo;
    }

    /**
     * Set wsrWpNo.
     * @param wsrWpNo wsrWpNo
     */
    public void setWsrWpNo(String wsrWpNo) {
        this.wsrWpNo = wsrWpNo;
    }

    /**
     * Get wsrRepDt.
     * @return wsrRepDt
     */
    @Column(name = "wsrRepDt")
    public String getWsrRepDt() {
        return this.wsrRepDt;
    }

    /**
     * Set wsrRepDt.
     * @param wsrRepDt wsrRepDt
     */
    public void setWsrRepDt(String wsrRepDt) {
        this.wsrRepDt = wsrRepDt;
    }

    public boolean equals(Object other) {
        if ((this == other)) {            
            return true;
        }
        if ((other == null)) {            
            return false;
        }
        if (!(other instanceof WpstarepId)) {            
            return false;
        }
        WpstarepId castOther = (WpstarepId) other;

        return (this.getWsrProjNo() == castOther.getWsrProjNo())
                && ((this.getWsrWpNo() == castOther.getWsrWpNo()) || (this.getWsrWpNo() != null
                        && castOther.getWsrWpNo() != null && this.getWsrWpNo().equals(castOther.getWsrWpNo())))
                && ((this.getWsrRepDt() == castOther.getWsrRepDt()) || (this.getWsrRepDt() != null
                        && castOther.getWsrRepDt() != null && this.getWsrRepDt().equals(castOther.getWsrRepDt())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getWsrProjNo();
        result = 37 * result + (getWsrWpNo() == null ? 0 : this.getWsrWpNo().hashCode());
        result = 37 * result + (getWsrRepDt() == null ? 0 : this.getWsrRepDt().hashCode());
        return result;
    }

}
