package model;
// Generated 15-Feb-2017 2:38:53 PM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * WpstarepId generated by hbm2java
 */
@SuppressWarnings("serial")
@Embeddable
public class WpstarepId implements java.io.Serializable {

    private int wsrProjNo;
    private String wsrWpNo;
    private String wsrRepDt;

    public WpstarepId() {
    }

    public WpstarepId(int wsrProjNo, String wsrWpNo, String wsrRepDt) {
        this.wsrProjNo = wsrProjNo;
        this.wsrWpNo = wsrWpNo;
        this.wsrRepDt = wsrRepDt;
    }

    @Column(name = "wsrProjNo", nullable = false)
    public int getWsrProjNo() {
        return this.wsrProjNo;
    }

    public void setWsrProjNo(int wsrProjNo) {
        this.wsrProjNo = wsrProjNo;
    }

    @Column(name = "wsrWpNo", nullable = false, length = 8)
    public String getWsrWpNo() {
        return this.wsrWpNo;
    }

    public void setWsrWpNo(String wsrWpNo) {
        this.wsrWpNo = wsrWpNo;
    }

    @Column(name = "wsrRepDt")
    public String getWsrRepDt() {
        return this.wsrRepDt;
    }

    public void setWsrRepDt(String wsrRepDt) {
        this.wsrRepDt = wsrRepDt;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof WpstarepId))
            return false;
        WpstarepId castOther = (WpstarepId) other;

        return (this.getWsrProjNo() == castOther.getWsrProjNo())
                && ((this.getWsrWpNo() == castOther.getWsrWpNo()) || (this.getWsrWpNo() != null
                        && castOther.getWsrWpNo() != null && this.getWsrWpNo().equals(castOther.getWsrWpNo())))
                && ((this.getWsrRepDt() == castOther.getWsrRepDt()) || (this.getWsrRepDt() != null
                        && castOther.getWsrRepDt() != null && this.getWsrRepDt().equals(castOther.getWsrRepDt())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getWsrProjNo();
        result = 37 * result + (getWsrWpNo() == null ? 0 : this.getWsrWpNo().hashCode());
        result = 37 * result + (getWsrRepDt() == null ? 0 : this.getWsrRepDt().hashCode());
        return result;
    }

}
